// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2qG6PHkUIx0nJWJQ73IYQLUlDiY5wEEA',
    appId: '1:494808083684:web:bdda73de63082f3f94d0f1',
    messagingSenderId: '494808083684',
    projectId: 'borsaapp-a6032',
    authDomain: 'borsaapp-a6032.firebaseapp.com',
    storageBucket: 'borsaapp-a6032.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8ILT63AJ3Dl7ivPZTMPwGondZwv1v4fY',
    appId: '1:494808083684:android:f6cdd2e3a0ee4b6d94d0f1',
    messagingSenderId: '494808083684',
    projectId: 'borsaapp-a6032',
    storageBucket: 'borsaapp-a6032.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlnplrQALXT1WADEon_GEq5nKrnQhPjno',
    appId: '1:494808083684:ios:770b4b11daed250794d0f1',
    messagingSenderId: '494808083684',
    projectId: 'borsaapp-a6032',
    storageBucket: 'borsaapp-a6032.firebasestorage.app',
    iosBundleId: 'com.example.borsaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlnplrQALXT1WADEon_GEq5nKrnQhPjno',
    appId: '1:494808083684:ios:770b4b11daed250794d0f1',
    messagingSenderId: '494808083684',
    projectId: 'borsaapp-a6032',
    storageBucket: 'borsaapp-a6032.firebasestorage.app',
    iosBundleId: 'com.example.borsaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2qG6PHkUIx0nJWJQ73IYQLUlDiY5wEEA',
    appId: '1:494808083684:web:25e9950da8ec034294d0f1',
    messagingSenderId: '494808083684',
    projectId: 'borsaapp-a6032',
    authDomain: 'borsaapp-a6032.firebaseapp.com',
    storageBucket: 'borsaapp-a6032.firebasestorage.app',
  );
}
